### ISSUE TITLE
CTM chunk border bug

### ISSUE THREAD

**Issue by Srdjan-V** [Meldexun/Nothirium#7]
**Describe the bug**
Blocks with ctm are not connecting properly

**Screenshots/Videos**

![2022-05-26_16 59 06](https://user-images.githubusercontent.com/78452357/170516050-8e4fec76-bd81-458c-b3bd-ca97e8d46ef3.png)
![2022-05-26_17 01 42](https://user-images.githubusercontent.com/78452357/170516062-a59b447f-5de6-43fa-bccd-e92036704c7f.png)

**Versions**
Nothirium: 0.1.1-beta
Entity Culling: 6.0.1-beta
RenderLib: 1.0.5
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): ctm

**Hardware**
CPU: Ryzen 3600
RAM: 16G 6 allocated 
GPU: gtx 1660 S
VRAM: 6G

**Comment by Meldexun** [comment]
Should be fixed with v1.12.2-0.1.3-beta

**Comment by Srdjan-V** [comment]
![2022-05-26_21 51 25](https://user-images.githubusercontent.com/78452357/170566420-f7829556-0064-488a-9825-8ec660111487.png)
It is still present with horizontally placed blocks

**Comment by Meldexun** [comment]
You could have reopened the issue since it wasn't fixed.

Anyway v1.12.2-0.1.4-beta fixes the issue completely
